src/fungible/amount.rs
Related: https://github.com/RGB-WG/rgb-core/pull/88
=> Add DecimalPrecision type

.gitignore, src/bin/rgb.rs, src/psbt.rs
=> Support OpretFirst (opret1st)

Cargo.lock, Cargo.toml, src/bin/rgb.rs
now that PR #14 has been merged, here's the change to psbt bundle CLI command again, ported to the master branch
=> psbt bundle: add close method + tapret + opret if needed

std/src/accessors/merge_reveal.rs
=> Fix missed transition merge in bundle merge op

src/pay.rs, std/src/interface/mod.rs, std/src/interface/suppl.rs
The result of the discussion at: https://github.com/orgs/LNP-BP/discussions/160
The related proposed standard for media kit information: https://github.com/orgs/LNP-BP/discussions/162
=> Add media information to the supplement

src/pay.rs, std/src/interface/builder.rs, std/src/persistence/inventory.rs
=> Account for address-based vout seals in consign procedure

src/invoice/builder.rs, src/invoice/invoice.rs, src/invoice/mod.rs, src/invoice/parse.rs, src/lib.rs
All the new stuff is in `builder.rs`. The stuff in 593c85ff51e72a2baa963a8fbcd5ae7ecb44e84c is just moving the code around to refactor mod into multiple files - with no changes inside.
=> Invoice builder API

.github/workflows/codecov.yml, .github/workflows/lint.yml, Cargo.lock, Cargo.toml, src/invoice/builder.rs, src/invoice/mod.rs, src/pay.rs, src/psbt/dbc.rs, src/psbt/lnpbp4.rs, src/psbt/opret.rs, src/psbt/tapret.rs, std/Cargo.toml, std/src/containers/transfer.rs, std/src/interface/iface.rs, std/src/interface/iimpl.rs, std/src/interface/rgb20.rs, std/src/interface/rgb21.rs, std/src/interface/rgb25.rs, std/src/persistence/stock.rs, std/src/reserved.rs, std/src/stl/mod.rs, std/src/stl/specs.rs, std/src/stl/stl.rs
Contains just updates to the dependencies and warning fixes
=> Release v0.10.9

src/interface/rgb21.rs, src/persistence/hoard.rs, src/persistence/inventory.rs
Alternative to https://github.com/RGB-WG/rgb-std/pull/108
Close #81 
Close #108
=> Fix blank transition builder

Cargo.lock, Cargo.toml, src/interface/builder.rs, src/stl/stl.rs
**Depends**
- https://github.com/RGB-WG/rgb-core/pull/201
=> Fix collection size convertion

src/persistence/inventory.rs
=> Do not update blindings for blank transitions

src/containers/partials.rs, src/persistence/inventory.rs
Part of solution for https://github.com/RGB-WG/rgb/issues/117
=> Make Batch to contain only unique tx prevout refs

src/interface/inheritance.rs
=> iface: break if overflow

src/interface/inheritance.rs
=> chore: refactor inheritance

Cargo.lock, Cargo.toml, src/containers/consignment.rs, src/containers/indexed.rs, src/interface/builder.rs, src/persistence/hoard.rs, src/persistence/inventory.rs, src/persistence/stash.rs
Counterparty to https://github.com/RGB-WG/rgb-core/pull/236
=> Move asset tags to genesis

Cargo.lock, src/containers/anchors.rs, src/persistence/memory.rs, src/persistence/stash.rs, src/persistence/stock.rs
=> Resolve secret seals before indexing consignment

src/accessors/merge_reveal.rs, src/containers/anchors.rs
Closes problem from https://github.com/RGB-WG/rgb/commit/ce07eb74a091baaab29632070ab689c59aca2573 and closes #196
=> Fix anchor operations

invoice/src/amount.rs, invoice/src/builder.rs, invoice/src/lib.rs
Coin amount is a helper type for displaying values with precision
=> Coin amount type

src/interface/builder.rs, src/interface/iimpl.rs, src/persistence/stock.rs
add method for metadata and other interface features
=> more-interface-features

invoice/src/parse.rs
Addresses review https://github.com/RGB-WG/rgb-std/issues/208
=> Require invoice URIs not to contain authority

invoice/src/invoice.rs, invoice/src/parse.rs
=> fix: invoice baid64 encode & decode for P2TR address

Cargo.lock, Cargo.toml, invoice/src/invoice.rs, src/containers/consignment.rs, src/interface/builder.rs
This PR updates rgb-std to be compatible with the [latest Network changes](https://github.com/BP-WG/bp-std/pull/32), including support for Testnet4. 
It also fixes a compilation error encountered during the development process.
If you have any suggestions, please leave your valuable comments, I will actively cooperate with the revision, thank you very much
=> Support Testnet4 Network

Cargo.lock, Cargo.toml, src/containers/consignment.rs, src/containers/indexed.rs, src/contract/assignments.rs, src/contract/mod.rs, src/interface/contract.rs, src/interface/resolver.rs, src/persistence/memory.rs, src/persistence/state.rs, src/persistence/stock.rs, src/resolvers.rs
Counterpart for https://github.com/RGB-WG/rgb-core/pull/265
=> Chore: use new witness-related type names from RGB Core

src/persistence/memory.rs
=> Fix invalid interface abstraction in MemStash::impl_for

src/contract/assignments.rs
=> Allow storing state assigned to alternative witness transactions

Cargo.lock, Cargo.toml, cli/src/dump.rs, cli/src/exec.rs, src/lib.rs, src/mound.rs, src/pile.rs, src/popls/bp.rs, src/stockpile.rs
Based on:
- https://github.com/BP-WG/bp-core/pull/112
- https://github.com/RGB-WG/rgb-core/pull/286
=> Differentiate witness txo-based seals from existing utxo-based seals
