RGB-WG/rgb-std

src/fungible/allocation.rs

The trait `IntoSealValueMap` cannot be implemented by `OutpointValueVec` and `OutpointValueMap` because the method `into_seal_value_map` cannot pass CloseMethod as a parameter.

Remove incomplete converts

---

Cargo.lock
Cargo.toml
src/bin/rgb.rs

completing an RGB transfer using the CLI currently requires the user to prepare the PSBT to hold the committment (before `psbt bundle` for opret or afterwards for tapret), and there is no CLI command to do so (one either needs to use `descriptor-wallet` for walleting or write one in rust)
this PR attepmts to drop such requirement by adding the close method as an optional parameter (tapret as default, like for the `blind` command) and, if needed, automatically set tapret DFS path or opret host
this change should allow users to create PSBTs with their wallet software of choice and still be able to use the CLI to transfer RGB assets
PS: opening this on branch v0.8 instead of master as the `.set_opret_host` method is not available there (yet)

add tapret DFS path or opret host in psbt bundle CLI command

---

Cargo.lock
Cargo.toml
src/invoice.rs
src/lib.rs
src/pay.rs
src/psbt/dbc.rs
src/psbt/lnpbp4.rs
src/psbt/mod.rs
std/src/containers/mod.rs
std/src/containers/seal.rs
std/src/interface/builder.rs
std/src/interface/contract.rs
std/src/interface/iimpl.rs
std/src/interface/suppl.rs
std/src/persistence/hoard.rs
std/src/persistence/inventory.rs
std/src/persistence/mod.rs
std/src/persistence/stash.rs
std/src/persistence/stock.rs

Last epic on the way to v0.10 completion

Invoice payment implementation

---

src/invoice.rs
src/pay.rs

To support invoices without a specified RGB amount I was about to change the `value` field of the `RgbInvoice` struct from `u64` to an `Option<u64>`, but then I've noticed a TODO comment saying that `value` should be a `TypedState` field, so I've done that instead. I hope it's good enough. I've left a TODO comment (partially extracted from the removed one) for stuff that I don't see as urgent right now but eventually I'll open a PR for that too.

RgbInvoice: change value from u64 to TypedState

---

src/psbt/dbc.rs

This small PR fixes the count of output commitment hosts in `dbc_conclude`.
It counted all outputs, now only counts ones containing commitment hosts, as intended.

Fix dbc_conclude commitment host count

---

src/invoice.rs
src/pay.rs

This PR makes the `contract` field of the `RgbInvoice` struct optional.
As discussed in a previous call this allows use cases where a user wants to receive an asset but doesn't care about which asset (e.g. collectibles donation).

RgbInvoice: make contract optional

---

Cargo.lock
Cargo.toml
src/invoice.rs
src/pay.rs

This PR changes `RgbInvoice`:
- using the `~` character to denote empty path prameters
- making the `iface` field optional
- adding the `expiry` field
- improving the handling of unknown query parameters
Note: the `~` character has been introduced because having both contract ID and iface optional broke url parsing when they were both missing.

make iface optional and add expiry

---

src/psbt/mod.rs

This PR adds support for automatically setting opret/tapret host if needed.
The implementation is similar to my previous rgb-std PRs #14 and #15.
Note: I made the `opret` and `tapret` modules from `psbt` public (and not just `pub(crate)`) as they're also useful outside of rgb-wallet (e.g. we need to use `opret` in rgb-lib).

set opret/tapret host if needed

---

Cargo.lock
Cargo.toml
src/invoice.rs
src/lib.rs

This PR adds parsing for the `RgbTransport` from the invoice's scheme.
The format for the transport I chose is `<transport><tls>-<host>`, where:
- `<transport>` is the transport name (with no `-` character, as it's used to separate the host portion)
- `<tls>` is `0` for cleartext and `1` is for tls
- `<host>` is the transport host (can contain `-` characters)
I (temporarily) commented RestHttp, WebSockets and Storm variants as they're now unused.
I also moved the `map_query_params` function out of `RgbInvoice` as it doesn't use self (as noted in a previous PR).
In the context of issue #34, I kept the tls parameter (to avoid breaking URL integrity) but used 0/1 for brevity and didn't use the `+` charachter, which I plan to use to support multiple transports (did a minimal test …

add invoice transport parsing

---

std/src/interface/contract.rs
std/src/interface/rgb20.rs

This should significantly simplify wallet APIs such that contract interfaces will now return only a state which is specific to some wallet descriptor.

Add OutpointFilter to filter wallet-based outputs

---

src/lib.rs
src/pay.rs
src/psbt/mod.rs
src/psbt/rgb.rs
std/src/interface/suppl.rs

Closes #73
Please keep in mind that with this change if you'd like to use velocity classes you need to assign to your PSBT outputs a new proprietary key indicating the velocity class you are using.

Fix use of velocity classes

---

Cargo.lock
Cargo.toml
std/src/interface/builder.rs
std/src/persistence/stock.rs

Fixes #80
The bug was caused by the fact that we do state update only on consignment consumation - and not on production of state transitions. This PR fixes that.

Add blank state transitions to state

---

std/src/stl/mod.rs
std/src/stl/stl.rs

I figured I'd just go ahead and make all the methods under stl/stl pub.

Export rgb-core LIB_ID_RGB constant

---

Cargo.lock
src/interface/builder.rs
src/interface/mod.rs

I found a way how not to require a user to manually construct `AssetTag` each time - but still provide an ability to set custom asset tag when needed (for instance for Liquid assert bridges).
This reduces the complexity of moving from v0.10 to v0.11 downstream

Update to use automatically-generated asset tags

---

src/interface/builder.rs

Since `Terminal.seals` is a `SmallXxx` collection, so the seal quantity may reach up to 65535, then the corresponding builder should allow seal quantity up to 65535.
```rust
pub struct Terminal {
pub seals: SmallOrdSet<TerminalSeal>,
pub tx: Option<Tx>,
}
```
It's not a protocol change, if you wish I can port this fix to `v0.10` branch.

ifaces: use correct fungible builder type

---

src/accessors/bundle.rs
src/accessors/merge_reveal.rs
src/persistence/hoard.rs

**Description**
This PR intent fix the merge reveal bundle check. Also, adjusts the error message for correct naming.

Fix bundle merge reveal check

---

Cargo.lock
Cargo.toml
invoice/src/builder.rs
invoice/src/invoice.rs
invoice/src/lib.rs
invoice/src/parse.rs
src/accessors/assignments.rs
src/accessors/bundle.rs
src/containers/consignment.rs
src/containers/indexed.rs
src/containers/mod.rs
src/containers/partials.rs
src/containers/seal.rs
src/containers/transfer.rs
src/containers/util.rs
src/containers/validate.rs
src/interface/builder.rs
src/interface/contract.rs
src/persistence/hoard.rs
src/persistence/inventory.rs
src/persistence/stock.rs
src/stl/stl.rs
stl/RGBStd@0.1.0.sty

Blind UTXO ("secret seals") was not properly supporting cross-chain seal definitions. This resulted in the bug where the accepted consignment was not recognized as its own state.
The core of the fix is in https://github.com/RGB-WG/rgb-core/pull/199, as well as in https://github.com/BP-WG/bp-core/pull/71
This required making blind UTXOs commit to the chain. I used this as an opportunity to embed multi-chain support to RGB invoices and combine it with testnet etc indications. So now, the beneficiary in the invoice ALWAYS contains information on both network and chain, using new prefixes: `bc`, `tb`, `lq`, `tl` etc:
1) if the beneficiary is an address, it will look like `bc:1pj6fx-pzy9gy-xl6mek-j7fxgm-h3frl5-fwulrf-lawxpt-vve6jv-h4vles-hh8wut` or `bc:18cBEM-RxXHqz-WWCxZN-tU91F5-sbUNKh-L5PX` …

Cross-chain secret seals. New network/chain in invoices

---

src/persistence/inventory.rs

When sending an asset allocated to an UTXO that has also other assets allocated we need to construct the blank transitions (using the `blank_builder` method).
But when doing
```rust
blank_builder = blank_builder
.add_input(opout, state.clone())?
.add_owned_state_raw(opout.ty, seal, state)?;
```
the call to `add_owned_state_raw` raises the `AssetTagMissed` error (from the internal call to the `asset_tag` method), because `self.asset_tags` is empty.
With the proposed fix this error doesn't arise anymore. The fix consists in calling `add_asset_tag_raw` the same way it's currently done in the `transition_builder` method.

fix blank_builder to avoid AssetTagMissed error

---

Cargo.lock
Cargo.toml
invoice/src/amount.rs
invoice/src/builder.rs
invoice/src/invoice.rs
invoice/src/parse.rs
src/interface/builder.rs
src/interface/contract.rs
src/interface/filters.rs
src/interface/mod.rs
src/interface/rgb20.rs
src/interface/rgb21.rs
src/persistence/hoard.rs
src/persistence/inventory.rs
src/persistence/mod.rs
src/persistence/state.rs
src/persistence/stock.rs
src/stl/error.rs
src/stl/stl.rs

Prerequisites for https://github.com/RGB-WG/rgb/pull/92. Include:
- new concept of witness filters;
- new concept of state change types which help to track past operation effects
- `AmountChange`: a case of state change type which tracks the change in the balance as an effect of past fungible transfers
- refactored typed states
- `ContractIface::fungible_ops` command reconstructing history of operations affecting some fungible state (with changes expressed as AmountChange)
- `Rgb20::transfer_history` wrapper which simplifies the call for RGB20-interfaces contracts

Fungible operation history

---

invoice/src/builder.rs

This fixed #131 by removing the `UnspecifiedMeans` transport that is used to initially populate the invoice's `transports` field when adding more transports.

drop unspecified transport when adding new ones

---

invoice/src/builder.rs
invoice/src/data.rs
invoice/src/invoice.rs
invoice/src/lib.rs
invoice/src/parse.rs
src/interface/builder.rs
src/interface/contract.rs
src/interface/rgb21.rs
src/persistence/inventory.rs
src/stl/chain.rs

**Description**
This PR intent solve two issues:
- Add support to data invoice for non-fungible (rgb21, ...)
- Add support to readable precision for fungible (rgb20, rgb25, ...)
Close #133 
Close #121

Support to non-fungible invoices and readable precision

---

Cargo.lock
Cargo.toml
src/accessors/merge_reveal.rs

This PR fixes https://github.com/RGB-WG/rgb/issues/101
The bug was that the method `merge_reveal` (implemented for the `TransitionBundle`) was calling `extend` assuming that `other` had more revealed data than `self`. This is not always the case, so the updated version merges the structures keeping the most revealed condition among the two.

fix TransitionBundle merge_reveal

---

src/persistence/inventory.rs

This PR fixes the contract ID used for blank transitions.
Fixes https://github.com/RGB-WG/rgb/issues/116

fix contract ID for blank transitions

---

src/interface/builder.rs

This PR changes the `OperationBuilder` map fields from `HashMap`s to `BTreeMap`s, allowing to construct deterministic transitions (because `BTreeMap` is an ordered map, while with the `HashMap` we cannot guarantee the inserted pairs are always in the same order)

convert OperationBuilder map fields to BTreeMap

---

src/accessors/merge_reveal.rs

This PR removes a check performed in the `TransitionBundle::merge_reveal` method, which makes sure the transition bundle's `input_map` is not longer than the transition bundle's `known_transitions`. The check is making impossible to accept the consignment for the last trasfer in this scenario:
```
┌─┐                    ┌─┐              ┌─┐   
║"│                    ║"│              ║"│   
└┬┘                    └┬┘              └┬┘   
┌┼┐                    ┌┼┐              ┌┼┐   
│                      │                │    
┌┴┐                    ┌┴┐              ┌┴┐   
Alice                   Bob            Charlie 
────┐                  │                │    
│ 666 (issuance)   │                │    
<───┘                  │                │    
│                      │ …
```

remove check in TransitionBundle::merge_reveal

---

src/interface/builder.rs
src/persistence/inventory.rs

This builds on top of https://github.com/RGB-WG/rgb-std/pull/141
While analysing https://github.com/RGB-WG/rgb-std/issues/149 I have noticed that we redundantly provide builder with contract id twice: during instantiation and on completion.

Fix redundant contract_id in builders

---

Cargo.lock
src/persistence/stock.rs

This is required for performing dump of stash objects to YAML in command-line

Add serde serialization for index types

---

src/containers/consignment.rs

**Description**
This PR intent solve the problem noticed in #164.  
When we "reassemble" the ID from a string, the methods use HRI as a prefix, but the current Display uses "consignment" as a prefix. I ajusted the display of the `ConsignmentId` to use "con" as prefix. 
Closes #164

Fix Consignment ID Parse

---

Cargo.lock
Cargo.toml
invoice/src/builder.rs
invoice/src/invoice.rs
invoice/src/lib.rs
invoice/src/parse.rs
src/persistence/stock.rs

Closes #198 and #119
I decided to address this two issues simultaneously, since it is impossible to reliable parse chunked variable-length strings; thus, in order to get chunking I had to switch to Base64 and fixed-length strings. Since we had to move from bitcoin address format with that, I used the approach as a base to add closing method in a compact form (one byte).

Support custom close methods in vout-based invoices

---

src/containers/consignment.rs

Description: for this pull request,
1.check that interface ids match implementations(check iface id matches iface id presents in iimpl)
2.check bundle ids listed in terminals are present in the consignment(get bundle ids from indexconsignment, then check if the bundle id set contains the bundle id in the terminals)
Question: about the `check attach ids from data containers are present in operations`
I don't understand it, should we check whether the attach id from the consignment is equal to the opid present in the operations?(I mean check if the attach id is equal to the opid? If not, where do the operations come from?)
Or should we check the own state from the state transition, then check the attach id in the revealed attach state is equal to the attach id in the consignment?

check ifaceid, bundleid in consignment

---

invoice/src/amount.rs

As agreed in https://github.com/RGB-WG/rgb-std/pull/204#issuecomment-2162967905, this PR drops the `` ` `` and `'` characters from the list of possible group separators for `CoinAmount`.

drop tick and backtick from amount group separator list

---

src/interface/contract.rs

Description: 
now, there are `fungible_ops`, and `data_ops` related to `FungibleAllocation`, and `DataAllocation`, so I think we can also have `rights_ops`, `attachment_ops` related to `RightsAllocation`, `AttachAllocation`.
1. add `rights_ops` interface
2. add `attachment_ops` interface

add rights, attachment operations

---

src/persistence/stock.rs

This PR fixes a typo I noticed while testing with rgb-sandbox.

fix now -> not typo

---

src/interface/iimpl.rs

Description: warn about repeated field names in the iface impl.
1. new `RepeatWarning` enum type for warning about the repeated field name and counts.
2. new `RepeatedStatus` for adding the repeated warnings into a vector.
4. use hashmap to check the repeated times in the metadata, global state, valencies, transitions, and extensions.
5. modified error, now is `(RepeatedStatus, Vec<ImplInconsistency>)`

warn about repeated field name in iimpl

---

invoice/src/data.rs

Background:
In the rgb21 contract, we have `error fractionOverflow
"The amount of token fractions in outputs exceeds 1"`, so I think maybe we should have a check add/sub-operation to check if or not the owned fraction is overflow(or the other fraction checks for add/sub-operation), also we can make a change for the allocation. It's similar to the rgb20 amount.
Description:
add `check_add`, `check_sub`, `check_addassign`, `check_subassign`, and other methods for the `Ownedfraction`.

check add and sub operation for owned fraction

---

src/interface/contract.rs

Background:
Based on https://github.com/RGB-WG/rgb-std/pull/227, there is also an `unreachable` in the rgb20 amount, so I think maybe we can change to the `Ord` in order to get rid of unreachable.
Description:
remove the `unreachable` in the rgb20 amount state change, then use the `Ord`. Similar to the rgb21 owed fraction state change.

unreachable to ord for amount

---

src/persistence/memory.rs
src/persistence/stash.rs
src/persistence/stock.rs

Description:
1. add a `get_sigs` interface for obtaining the content_sig in order to collect signatures. (the reason for adding this interface is that there are `add_supplyment`, and `supplement` interfaces for adding and obtaining the supplement, and then I noticed that there is an `import_sigs` interface, but no method to get content signature by content ID, so I think maybe we need an interface to obtain the content signature)
2. collect supplements.
3. test cases.

Collect supplyment features in consign

---

src/persistence/stash.rs
src/persistence/stock.rs

Description:
1. Add `sigs_for` in the stash reader provider
2. Collect genesis, scheme, iface, and iimpl signatures from the stash provider
Questions: I don't understand the following `TODO`
1. Conceal everything we do not need. (conceal seal, transition, and state?)
2. Add known sigs to the consignment. (What's the difference from the `collect signatures from the stash`?)
And the `know sigs`, do you mean the content signatures from the stash or the signatures from the disclosure? (In the Disclosure, there is `PublicKey, Signature` Key-Value map).

collect signatures from the stash

---

src/persistence/fs.rs
src/persistence/index.rs
src/persistence/memory.rs
src/persistence/mod.rs
src/persistence/stash.rs
src/persistence/state.rs
src/persistence/stock.rs

Counterpart to https://github.com/BP-WG/bp-wallet/pull/44
Provides more efficient and clearer way to ensure that the data are always persisted to disk when needed.

Refactor FS store and load workflows

---

Cargo.lock
src/containers/partials.rs
src/contract/mod.rs
src/persistence/memory.rs

Counterpart for https://github.com/RGB-WG/rgb-core/pull/264

Support contract state computation during validation

---

src/persistence/stock.rs

This is an enhancement over #246 which allows to spend from both opret and tapret inputs at the same time.
I am not sure whether it is worth adding it since it adds a lot of code and logic complexity - or is it just better to stick with UX-based solution I have described in https://github.com/RGB-WG/rgb-std/issues/246#issuecomment-2284812331

Allow to pay from both tapret and opret inputs

---

src/containers/mod.rs
src/containers/partials.rs
src/interface/builder.rs
src/persistence/stock.rs

Closes #246
If PSBT inputs contain single-use seals of different types (opret and taproot) spent by the same wallet, we need to create two state transitions - one for tapret and one for opret. The main state transition is the one which matches the type of the wallet descriptor; the other state transition will just transform invalid seal type into correct one allocated to the change output. We also have to construct blank transitions of both types, as needed.
If PSBT is multi-party with wallets of different seal types, this situation doesn't happen since each wallet works and updates PSBT independently and their state transitions does not cross.

Support spending mixed opret/tapret outputs

---

src/contract/assignments.rs

Required for supporting LN channels. Closes #238

Iignore the difference in state and seals of output assignments

---

src/persistence/stock.rs

Closes #262
Requires https://github.com/RGB-WG/rgb/pull/240

Require just one secret seal for the transfer method

---

src/contract/assignments.rs
src/contract/mod.rs
src/interface/contract.rs
src/interface/filter.rs
src/interface/iface.rs
src/interface/mod.rs
src/lib.rs
src/persistence/memory.rs
src/persistence/state.rs
src/persistence/stock.rs

Prerequisites for fixing operation history issue https://github.com/RGB-WG/rgb/issues/252 with https://github.com/RGB-WG/rgb/pull/253
This also completes support for NFTs and any possible state types in RGB standard library

Fixing operation history

---

src/containers/indexed.rs
src/interface/contractum.rs
src/persistence/memory.rs
src/persistence/stock.rs

This PR fixes the build on nightly. @dr-orlovsky I have used 0.11 beta 9 as base for the commit and would be glad if you could release a beta 9.1 for this (it would fix the new CI job added in https://github.com/RGB-WG/rgb-tests/pull/25)

fix nightly build and lint

---

src/containers/partials.rs
src/persistence/index.rs
src/persistence/memory.rs
src/persistence/stock.rs

Includes fix from #289 
Closes #290

Use XOupoint instead of XOutputSeal in the APIs

---

Cargo.lock
Cargo.toml
cli/src/dump.rs
src/contract.rs
src/info.rs
src/lib.rs
src/mound.rs
src/pile.rs
src/popls/bp.rs
src/providers/fs.rs
src/providers/mod.rs
src/stockpile.rs

This reduces attack surface my removing many previously exposed internals of the library.
Based on https://github.com/AluVM/sonic/pull/15

Make v0.12 APIs more consistent

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
src/contract.rs
src/contracts.rs
src/lib.rs
src/popls/bp.rs

This PR moves sync method from `rgb` repo to `rgb-std`, making its implementation efficient and fully abstracted from a specific wallet provider and indexer

Implement efficient sync procedure
